services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: business-manage-app
    container_name: erp-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - erp-network

  webserver:
    image: nginx:alpine
    container_name: erp-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker-config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - erp-network

  db:
    image: mysql:8.0
    container_name: erp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: manage
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
      - ./manage.sql:/docker-entrypoint-initdb.d/manage.sql
    networks:
      - erp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: erp-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 128M
    depends_on:
      - db
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge

volumes:
  dbdata:
    driver: local